website:
  title: "LIVCorsika"
  search: true
  navbar:
    background: primary
    logo: "img/logo/logo.png"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Examples"
        menu:
        - text: "Writting QMarkdown"
          href: "doc/Examples/example1.qmd"
        - text: "Writting LaTeX"
          href: "doc/Examples/example2.qmd"
      - href: https://github.com/BridgeQG/LIVCorsika
        text: "GitHub Project"
      - href: about.qmd

bibliography: bib/references.bib
csl: bib/journal-of-cosmology-and-astroparticle-physics.csl

project:
  type: website

filters:
  - lua/latex-to-quarto.lua

format:
  html:
    theme: cosmo
    math: mathjax
    css: include/css-config.css
    